# Generated by Django 4.1.1 on 2023-01-03 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_auctionlisting_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="starting_bid",
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=11),
            preserve_default=False,
        ),
    ]
