# Generated by Django 4.1.1 on 2023-01-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_auctionlisting_starting_bid"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="watchlist",
            field=models.ManyToManyField(default=[], to="auctions.auctionlisting"),
        ),
    ]
