# Generated by Django 4.1.1 on 2023-01-07 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_user_watchlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="bids",
            name="bid",
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name="bids",
            name="listing",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auctions.auctionlisting",
            ),
        ),
        migrations.AddField(
            model_name="bids",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="listingcomments",
            name="comment",
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="listingcomments",
            name="listing",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auctions.auctionlisting",
            ),
        ),
        migrations.AddField(
            model_name="listingcomments",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="bids",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="listingcomments",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
