# Generated by Django 4.1.1 on 2023-01-07 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_bids_bid_bids_listing_bids_user_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Bids",
            new_name="Bid",
        ),
        migrations.RenameModel(
            old_name="ListingComments",
            new_name="ListingComment",
        ),
    ]
