# Generated by Django 4.1.1 on 2023-01-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_bid_bid_date_listingcomment_comment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="bid_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="listingcomment",
            name="comment_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
