# Generated by Django 4.1.1 on 2023-01-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0011_alter_bid_listing_alter_bid_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="is_closed",
            field=models.BooleanField(default=False),
        ),
    ]
