# Generated by Django 4.1.1 on 2023-01-10 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0012_auctionlisting_is_closed"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="winner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="winner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
