# Generated by Django 4.1.1 on 2023-01-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0013_auctionlisting_winner"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="sold_date",
            field=models.DateTimeField(null=True),
        ),
    ]
