# Generated by Django 4.1.1 on 2023-01-15 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0014_auctionlisting_sold_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listingcomment",
            name="listing",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="auctions.auctionlisting",
            ),
        ),
    ]
